#A tester
#https://scheele.hashnode.dev/build-a-dockerized-fastapi-application-with-poetry-and-gunicorn

FROM python:3.11.6-slim-bullseye
#A retester avec 3.11.6-alpine3.18
LABEL authors="Derfulio"

ENTRYPOINT ["top", "-b"]