# This workflow will install Python dependencies with Poetry, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python Poetry application test

on:
  push:
    branches: [ "main" ]
  pull_request:

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./apps/back
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.11
      uses: actions/setup-python@v3
      with:
        python-version: "3.11"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install poetry
        # Remove all the files of the current environment of the folder we are in
        POETRY_LOCATION=`poetry env info -p` 
        echo "Poetry is $POETRY_LOCATION"
        poetry env remove $POETRY_LOCATION
        rm -rf "$POETRY_LOCATION"
